name: "Publish on Flakehub"
on:
  push:
    branches:
      - "main"
jobs:
  publish:
    runs-on: "ubuntu-latest"
    permissions:
      id-token: "write"
      contents: "read"
    steps:
      - name: Checkout
        uses: "actions/checkout@v4"
      - name: Install Nix
        uses: "DeterminateSystems/nix-installer-action@main"
      - name: Setup Nix Cache
        uses: DeterminateSystems/magic-nix-cache-action@main
      - name: Push to Flakehub
        uses: "DeterminateSystems/flakehub-push@main"
        with:
          visibility: "public"
          rolling: true
